spring.application.name=code

# MySQL
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Actuator
management.endpoint.health.show-details=always
management.health.db.enabled=true